# Generated by Django 4.2.1 on 2023-05-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FakeUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=128)),
                ('password', models.CharField(max_length=128)),
                ('fake_username', models.CharField(max_length=128)),
                ('age', models.IntegerField(max_length=2)),
            ],
        ),
    ]
