# Generated by Django 4.2.1 on 2023-05-10 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeuser',
            name='age',
            field=models.IntegerField(),
        ),
    ]
