# Generated by Django 4.2.1 on 2023-05-10 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_fakeuser_age'),
    ]

    operations = [
        migrations.CreateModel(
            name='Good_Reasons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('reason', models.TextField()),
            ],
        ),
    ]
