# Generated by Django 4.2.1 on 2023-05-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_good_reasons'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Good_Reasons',
            new_name='GoodReasons',
        ),
    ]
