# Generated by Django 4.2.1 on 2023-06-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_rename_good_reasons_goodreasons'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fakeuser',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='fakeuser',
            name='fake_username',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='fakeuser',
            name='password',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
